var exampleSoundCloudSoundObject = {
    sounds: [{
        "artwork_url": "https://i1.sndcdn.com/artworks-000249686598-zk4k56-large.jpg",
        "commentable": true,
        "comment_count": 21,
        "created_at": "2017-10-31T17:18:00Z",
        "description": "https://bigwax.fr/en/in-love-with-a-ghost/music/healing\n\nheyyy we're finally making vinylss, pre order starting now and in stock the 11/12/2017\n\nhave a nice halloween : - )",
        "downloadable": false,
        "download_count": 0,
        "download_url": null,
        "duration": 26986,
        "full_duration": 26986,
        "embeddable_by": "all",
        "genre": "",
        "has_downloads_left": true,
        "id": 349473727,
        "kind": "track",
        "label_name": null,
        "last_modified": "2017-10-31T17:18:01Z",
        "license": "all-rights-reserved",
        "likes_count": 411,
        "permalink": "healing-vinyls",
        "permalink_url": "https://soundcloud.com/in-love-with-a-ghost/healing-vinyls",
        "playback_count": 8925,
        "public": true,
        "publisher_metadata": { "id": 349473727, "urn": "soundcloud:tracks:349473727" },
        "purchase_title": null,
        "purchase_url": null,
        "release_date": null,
        "reposts_count": 55,
        "secret_token": null,
        "sharing": "public",
        "state": "finished",
        "streamable": true,
        "tag_list": "electroniiiiiiccccccccc-bubble",
        "title": "healing vinyls",
        "uri": "https://api.soundcloud.com/tracks/349473727",
        "urn": "soundcloud:tracks:349473727",
        "user_id": 67527478,
        "visuals": null,
        "waveform_url": "https://wis.sndcdn.com/gH0VHr6F601g_m.json",
        "display_date": "2017-10-31T17:18:00Z",
        "domain_lockings": [],
        "monetization_model": "BLACKBOX",
        "policy": "MONETIZE",
        "user": { "avatar_url": "https://i1.sndcdn.com/avatars-000294734092-g34d5t-large.jpg", "first_name": "Maël", "full_name": "Maël", "id": 67527478, "kind": "user", "last_modified": "2017-10-31T17:04:32Z", "last_name": "", "permalink": "in-love-with-a-ghost", "permalink_url": "https://soundcloud.com/in-love-with-a-ghost", "uri": "https://api.soundcloud.com/users/67527478", "urn": "soundcloud:users:67527478", "username": "in love with a ghost", "verified": false, "city": "Paris", "country_code": "FR" },
        "playable": true,
        "_resource_id": 349473727,
        "_resource_type": "sound"
    }]
}